FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

MODEL_URL='https://storage.googleapis.com/test-model-elemental/model_lstm1.json'

CMD ["npm", "start"]
